In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('../Dataset//Vehicle Insurance Data//motor_data14-2018.csv')
df.head()

,SEX,INSR_BEGIN,INSR_END,EFFECTIVE_YR,INSR_TYPE,INSURED_VALUE,PREMIUM,OBJECT_ID,PROD_YEAR,SEATS_NUM,CARRYING_CAPACITY,TYPE_VEHICLE,CCM_TON,MAKE,USAGE,CLAIM_PAID
0,0,08-AUG-17,07-AUG-18,08,1202,519755.22,5097.83,5000029885,2007.0,4.0,6.0,Pick-up,3153.0,NISSAN,Own Goods,NaN
1,0,08-AUG-16,07-AUG-17,08,1202,519755.22,6556.52,5000029885,2007.0,4.0,6.0,Pick-up,3153.0,NISSAN,Own Goods,NaN
2,0,08-AUG-15,07-AUG-16,08,1202,519755.22,6556.52,5000029885,2007.0,4.0,6.0,Pick-up,3153.0,NISSAN,Own Goods,NaN
3,0,08-AUG-14,07-AUG-15,08,1202,519755.22,5102.83,5000029885,2007.0,4.0,6.0,Pick-up,3153.0,NISSAN,Own Goods,NaN
4,0,08-AUG-17,07-AUG-18,08,1202,1400000.00,13304.87,5000029901,2010.0,4.0,7.0,Pick-up,2494.0,TOYOTA,Own Goods,NaN

In [3]:
df['CLAIM_PAID'].fillna(0 , inplace=True)
df.head()

,SEX,INSR_BEGIN,INSR_END,EFFECTIVE_YR,INSR_TYPE,INSURED_VALUE,PREMIUM,OBJECT_ID,PROD_YEAR,SEATS_NUM,CARRYING_CAPACITY,TYPE_VEHICLE,CCM_TON,MAKE,USAGE,CLAIM_PAID
0,0,08-AUG-17,07-AUG-18,08,1202,519755.22,5097.83,5000029885,2007.0,4.0,6.0,Pick-up,3153.0,NISSAN,Own Goods,0.0
1,0,08-AUG-16,07-AUG-17,08,1202,519755.22,6556.52,5000029885,2007.0,4.0,6.0,Pick-up,3153.0,NISSAN,Own Goods,0.0
2,0,08-AUG-15,07-AUG-16,08,1202,519755.22,6556.52,5000029885,2007.0,4.0,6.0,Pick-up,3153.0,NISSAN,Own Goods,0.0
3,0,08-AUG-14,07-AUG-15,08,1202,519755.22,5102.83,5000029885,2007.0,4.0,6.0,Pick-up,3153.0,NISSAN,Own Goods,0.0
4,0,08-AUG-17,07-AUG-18,08,1202,1400000.00,13304.87,5000029901,2010.0,4.0,7.0,Pick-up,2494.0,TOYOTA,Own Goods,0.0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 508499 entries, 0 to 508498
Data columns (total 16 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   SEX                508499 non-null  int64
 1   INSR_BEGIN         508499 non-null  object
 2   INSR_END           508499 non-null  object
 3   EFFECTIVE_YR       508496 non-null  object
 4   INSR_TYPE          508499 non-null  int64
 5   INSURED_VALUE      508499 non-null  float64
 6   PREMIUM            508486 non-null  float64
 7   OBJECT_ID          508499 non-null  int64
 8   PROD_YEAR          508436 non-null  float64
 9   SEATS_NUM          508404 non-null  float64
 10  CARRYING_CAPACITY  391665 non-null  float64
 11  TYPE_VEHICLE       508499 non-null  object
 12  CCM_TON            508493 non-null  float64
 13  MAKE               508494 non-null  object
 14  USAGE              508499 non-null  object
 15  CLAIM_PAID         508499 non-null  float64
dtypes: float64(7), int64(3), object(6)
memory usage: 62.1+ MB

In [5]:
si = SimpleImputer(strategy='mean')
si

SimpleImputer()

In [6]:
df[['CARRYING_CAPACITY']] = si.fit_transform(df[['CARRYING_CAPACITY']])

In [7]:
df.isnull().sum()

SEX                   0
INSR_BEGIN            0
INSR_END              0
EFFECTIVE_YR          3
INSR_TYPE             0
INSURED_VALUE         0
PREMIUM              13
OBJECT_ID             0
PROD_YEAR            63
SEATS_NUM            95
CARRYING_CAPACITY     0
TYPE_VEHICLE          0
CCM_TON               6
MAKE                  5
USAGE                 0
CLAIM_PAID            0
dtype: int64

In [8]:
df.dropna(inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 508382 entries, 0 to 508498
Data columns (total 16 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   SEX                508382 non-null  int64
 1   INSR_BEGIN         508382 non-null  object
 2   INSR_END           508382 non-null  object
 3   EFFECTIVE_YR       508382 non-null  object
 4   INSR_TYPE          508382 non-null  int64
 5   INSURED_VALUE      508382 non-null  float64
 6   PREMIUM            508382 non-null  float64
 7   OBJECT_ID          508382 non-null  int64
 8   PROD_YEAR          508382 non-null  float64
 9   SEATS_NUM          508382 non-null  float64
 10  CARRYING_CAPACITY  508382 non-null  float64
 11  TYPE_VEHICLE       508382 non-null  object
 12  CCM_TON            508382 non-null  float64
 13  MAKE               508382 non-null  object
 14  USAGE              508382 non-null  object
 15  CLAIM_PAID         508382 non-null  float64
dtypes: float64(7), int64(3), object(6)
memory usage: 65.9+ MB

In [9]:
def feature_engineering(df):
    df = df.copy()

    df['INSR_BEGIN'] = pd.to_datetime(df['INSR_BEGIN'] , errors='coerce')
    df['INSR_END'] = pd.to_datetime(df['INSR_END'] , errors='coerce')

    df['contract_duration'] = (df['INSR_END'] - df['INSR_BEGIN']).dt.days
    # Make sure numeric columns are numeric
    df["INSURED_VALUE"] = pd.to_numeric(df["INSURED_VALUE"], errors="coerce")
    df["PREMIUM"] = pd.to_numeric(df["PREMIUM"], errors="coerce")
    df["PROD_YEAR"] = pd.to_numeric(df["PROD_YEAR"], errors="coerce")
    df["EFFECTIVE_YR"] = pd.to_numeric(df["EFFECTIVE_YR"], errors="coerce")
    df["SEATS_NUM"] = pd.to_numeric(df["SEATS_NUM"], errors="coerce")
    df["CARRYING_CAPACITY"] = pd.to_numeric(df["CARRYING_CAPACITY"], errors="coerce")
    df["CLAIM_PAID"] = pd.to_numeric(df["CLAIM_PAID"], errors="coerce")

    # 1. INSURED VALUE
    df["log_INSURED_VALUE"] = np.log(df["INSURED_VALUE"])
    df["premium_to_value"] = df["PREMIUM"] / df["INSURED_VALUE"]

    # 2. PREMIUM
    df["log_PREMIUM"] = np.log(df["PREMIUM"])
    df["premium_per_seat"] = df["PREMIUM"] / df["SEATS_NUM"].replace(0, np.nan)
    df["premium_per_capacity"] = df["PREMIUM"] / df["CARRYING_CAPACITY"].replace(0, np.nan)

    # 3. VEHICLE AGE
    df["vehicle_age"] = df["EFFECTIVE_YR"] - df["PROD_YEAR"]

    # 4. USAGE (frequency encoding)
    usage_counts = df["USAGE"].value_counts(normalize=True)
    df["usage_freq"] = df["USAGE"].map(usage_counts)

    # 5. MAKE (frequency encoding)
    make_counts = df["MAKE"].value_counts(normalize=True)
    df["make_freq"] = df["MAKE"].map(make_counts)

    TYPE_VEHICLE_counts = df["TYPE_VEHICLE"].value_counts(normalize=True)
    df["TYPE_VEHICLE_freq"] = df["TYPE_VEHICLE"].map(TYPE_VEHICLE_counts)

    # # 6. CLAIM RATIOS
    # df["claim_to_premium"] = df["CLAIM_PAID"] / df["PREMIUM"]
    # df["claim_to_value"] = df["CLAIM_PAID"] / df["INSURED_VALUE"]

    return df


df = feature_engineering(df)

In [10]:
df.columns

Index(['SEX', 'INSR_BEGIN', 'INSR_END', 'EFFECTIVE_YR', 'INSR_TYPE',
       'INSURED_VALUE', 'PREMIUM', 'OBJECT_ID', 'PROD_YEAR', 'SEATS_NUM',
       'CARRYING_CAPACITY', 'TYPE_VEHICLE', 'CCM_TON', 'MAKE', 'USAGE',
       'CLAIM_PAID', 'contract_duration', 'log_INSURED_VALUE',
       'premium_to_value', 'log_PREMIUM', 'premium_per_seat',
       'premium_per_capacity', 'vehicle_age', 'usage_freq', 'make_freq',
       'TYPE_VEHICLE_freq'],
      dtype='object')

In [11]:
df['CLAIM_FLAG'] = (df['CLAIM_PAID'] > 0).astype(int)
df.head()

,SEX,INSR_BEGIN,INSR_END,EFFECTIVE_YR,INSR_TYPE,INSURED_VALUE,PREMIUM,OBJECT_ID,PROD_YEAR,SEATS_NUM,...,log_INSURED_VALUE,premium_to_value,log_PREMIUM,premium_per_seat,premium_per_capacity,vehicle_age,usage_freq,make_freq,TYPE_VEHICLE_freq,CLAIM_FLAG
0,0,2017-08-08,2018-08-07,8.0,1202,519755.22,5097.83,5000029885,2007.0,4.0,...,13.161113,0.009808,8.536570,1274.4575,849.638333,-1999.0,0.263786,0.041976,0.177325,0
1,0,2016-08-08,2017-08-07,8.0,1202,519755.22,6556.52,5000029885,2007.0,4.0,...,13.161113,0.012615,8.788215,1639.1300,1092.753333,-1999.0,0.263786,0.041976,0.177325,0
2,0,2015-08-08,2016-08-07,8.0,1202,519755.22,6556.52,5000029885,2007.0,4.0,...,13.161113,0.012615,8.788215,1639.1300,1092.753333,-1999.0,0.263786,0.041976,0.177325,0
3,0,2014-08-08,2015-08-07,8.0,1202,519755.22,5102.83,5000029885,2007.0,4.0,...,13.161113,0.009818,8.537551,1275.7075,850.471667,-1999.0,0.263786,0.041976,0.177325,0
4,0,2017-08-08,2018-08-07,8.0,1202,1400000.00,13304.87,5000029901,2010.0,4.0,...,14.151983,0.009503,9.495885,3326.2175,1900.695714,-2002.0,0.263786,0.328550,0.177325,0

In [12]:
df.isnull().sum()

SEX                          0
INSR_BEGIN                   0
INSR_END                     0
EFFECTIVE_YR               640
INSR_TYPE                    0
INSURED_VALUE                0
PREMIUM                      0
OBJECT_ID                    0
PROD_YEAR                    0
SEATS_NUM                    0
CARRYING_CAPACITY            0
TYPE_VEHICLE                 0
CCM_TON                      0
MAKE                         0
USAGE                        0
CLAIM_PAID                   0
contract_duration            0
log_INSURED_VALUE            0
premium_to_value             2
log_PREMIUM                  0
premium_per_seat         33688
premium_per_capacity    162176
vehicle_age                640
usage_freq                   0
make_freq                    0
TYPE_VEHICLE_freq            0
CLAIM_FLAG                   0
dtype: int64

In [13]:
df.dropna(inplace=True)

In [14]:
X = df.drop(columns=['CLAIM_FLAG' , 'CLAIM_PAID' , 'MAKE' , 'USAGE' , 'INSR_BEGIN' , 'INSR_END' , 'TYPE_VEHICLE' , 'OBJECT_ID'])
y = df.CLAIM_FLAG.values

In [15]:
X.isnull().sum()

SEX                     0
EFFECTIVE_YR            0
INSR_TYPE               0
INSURED_VALUE           0
PREMIUM                 0
PROD_YEAR               0
SEATS_NUM               0
CARRYING_CAPACITY       0
CCM_TON                 0
contract_duration       0
log_INSURED_VALUE       0
premium_to_value        0
log_PREMIUM             0
premium_per_seat        0
premium_per_capacity    0
vehicle_age             0
usage_freq              0
make_freq               0
TYPE_VEHICLE_freq       0
dtype: int64

In [16]:
X.dropna(inplace=True)

In [17]:
X.shape

(317503, 19)

In [18]:
y.shape

(317503,)

In [19]:
x_train , x_test , y_train , y_test = train_test_split(X , y , stratify=y , random_state=42)

In [20]:
x_train

,SEX,EFFECTIVE_YR,INSR_TYPE,INSURED_VALUE,PREMIUM,PROD_YEAR,SEATS_NUM,CARRYING_CAPACITY,CCM_TON,contract_duration,log_INSURED_VALUE,premium_to_value,log_PREMIUM,premium_per_seat,premium_per_capacity,vehicle_age,usage_freq,make_freq,TYPE_VEHICLE_freq
301680,0,13.0,1202,2235228.76,28728.33,2014.0,61.0,61.000000,0.0,364,14.619854,0.012853,10.265639,470.95623,470.956230,-2001.0,0.066600,0.000925,0.128996
64786,0,11.0,1202,203284.00,6604.99,1994.0,1.0,90.800000,0.0,364,12.222359,0.032491,8.795581,6604.99000,72.742181,-1983.0,0.263786,0.012068,0.185054
292371,2,14.0,1202,0.00,2312.60,1983.0,2.0,27.000000,1994.0,365,-inf,inf,7.746128,1156.30000,85.651852,-1969.0,0.157657,0.004784,0.185054
127980,0,41.0,1202,870000.00,11223.94,2006.0,1.0,159.800000,0.0,364,13.676248,0.012901,9.325804,11223.94000,70.237422,-1965.0,0.263786,0.041976,0.185054
164803,0,14.0,1201,714000.00,9288.30,2001.0,5.0,416.533046,1794.0,364,13.478638,0.013009,9.136511,1857.66000,22.299071,-1987.0,0.240376,0.328550,0.143406
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
212072,0,95.0,1202,1735785.07,16733.58,2013.0,1.0,1600.000000,9726.0,364,14.366970,0.009640,9.725173,16733.58000,10.458488,-1918.0,0.263786,0.001123,0.185054
408475,0,11.0,1202,0.00,777.39,2016.0,4.0,7.000000,2488.0,365,-inf,inf,6.655942,194.34750,111.055714,-2005.0,0.263786,0.041976,0.177325
401675,0,15.0,1202,2000000.00,6011.25,2015.0,1.0,15000.000000,11548.0,365,14.508658,0.003006,8.701388,6011.25000,0.400750,-2000.0,0.263786,0.025699,0.012662
233274,1,14.0,1202,0.00,371.10,2012.0,3.0,3.000000,395.0,364,-inf,inf,5.916472,123.70000,123.700000,-1998.0,0.169300,0.115539,0.208453
216927,0,11.0,1202,1713799.96,11651.90,2012.0,4.0,7.000000,2494.0,364,14.354224,0.006799,9.363225,2912.97500,1664.557143,-2001.0,0.263786,0.328550,0.177325

In [21]:
from sklearn.utils.class_weight import compute_class_weight
classe = np.unique(y_train)
weight = compute_class_weight(class_weight='balanced' , classes = np.unique(y_train) , y=y_train)
class_weights = dict(zip(classe , weight))
class_weights

{np.int64(0): np.float64(0.5466995123653495),
 np.int64(1): np.float64(5.853374956983433)}

In [22]:
from catboost import CatBoostClassifier
model = CatBoostClassifier(
    iterations=400,
    depth=10,
    learning_rate=0.05,
    loss_function='Logloss',
    eval_metric='AUC',
    verbose=100,
    random_seed=42,
    task_type='GPU',
    class_weights=class_weights)

In [23]:
model.fit(x_train , y_train , eval_set=(x_test , y_test) , plot=True)

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

Default metric period is 5 because AUC is/are not implemented for GPU

0:	test: 0.7523800	best: 0.7523800 (0)	total: 29ms	remaining: 11.6s
100:	test: 0.7749531	best: 0.7749531 (100)	total: 1.97s	remaining: 5.83s
200:	test: 0.7758314	best: 0.7760221 (185)	total: 3.88s	remaining: 3.85s
300:	test: 0.7748856	best: 0.7760221 (185)	total: 5.8s	remaining: 1.91s
399:	test: 0.7736532	best: 0.7760221 (185)	total: 7.67s	remaining: 0us
bestTest = 0.7760220766
bestIteration = 185
Shrink model to first 186 iterations.

In [24]:
from sklearn.metrics import classification_report


y_pred = model.predict(x_test)
print(classification_report(y_test , y_pred))

              precision    recall  f1-score   support

           0       0.97      0.61      0.75     72596
           1       0.16      0.81      0.27      6780

    accuracy                           0.63     79376
   macro avg       0.57      0.71      0.51     79376
weighted avg       0.90      0.63      0.71     79376

In [31]:
x_train = x_train.replace([np.inf, -np.inf], np.nan)
x_test = x_test.replace([np.inf, -np.inf], np.nan)

In [32]:
x_train.shape

(238127, 19)

In [33]:
x_train.isna().sum()

SEX                         0
EFFECTIVE_YR                0
INSR_TYPE                   0
INSURED_VALUE               0
PREMIUM                     0
PROD_YEAR                   0
SEATS_NUM                   0
CARRYING_CAPACITY           0
CCM_TON                     0
contract_duration           0
log_INSURED_VALUE       90246
premium_to_value        90246
log_PREMIUM                 2
premium_per_seat            0
premium_per_capacity        0
vehicle_age                 0
usage_freq                  0
make_freq                   0
TYPE_VEHICLE_freq           0
dtype: int64

In [34]:
df.dropna(inplace=True)

In [35]:
x_train

,SEX,EFFECTIVE_YR,INSR_TYPE,INSURED_VALUE,PREMIUM,PROD_YEAR,SEATS_NUM,CARRYING_CAPACITY,CCM_TON,contract_duration,log_INSURED_VALUE,premium_to_value,log_PREMIUM,premium_per_seat,premium_per_capacity,vehicle_age,usage_freq,make_freq,TYPE_VEHICLE_freq
301680,0,13.0,1202,2235228.76,28728.33,2014.0,61.0,61.000000,0.0,364,14.619854,0.012853,10.265639,470.95623,470.956230,-2001.0,0.066600,0.000925,0.128996
64786,0,11.0,1202,203284.00,6604.99,1994.0,1.0,90.800000,0.0,364,12.222359,0.032491,8.795581,6604.99000,72.742181,-1983.0,0.263786,0.012068,0.185054
292371,2,14.0,1202,0.00,2312.60,1983.0,2.0,27.000000,1994.0,365,NaN,NaN,7.746128,1156.30000,85.651852,-1969.0,0.157657,0.004784,0.185054
127980,0,41.0,1202,870000.00,11223.94,2006.0,1.0,159.800000,0.0,364,13.676248,0.012901,9.325804,11223.94000,70.237422,-1965.0,0.263786,0.041976,0.185054
164803,0,14.0,1201,714000.00,9288.30,2001.0,5.0,416.533046,1794.0,364,13.478638,0.013009,9.136511,1857.66000,22.299071,-1987.0,0.240376,0.328550,0.143406
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
212072,0,95.0,1202,1735785.07,16733.58,2013.0,1.0,1600.000000,9726.0,364,14.366970,0.009640,9.725173,16733.58000,10.458488,-1918.0,0.263786,0.001123,0.185054
408475,0,11.0,1202,0.00,777.39,2016.0,4.0,7.000000,2488.0,365,NaN,NaN,6.655942,194.34750,111.055714,-2005.0,0.263786,0.041976,0.177325
401675,0,15.0,1202,2000000.00,6011.25,2015.0,1.0,15000.000000,11548.0,365,14.508658,0.003006,8.701388,6011.25000,0.400750,-2000.0,0.263786,0.025699,0.012662
233274,1,14.0,1202,0.00,371.10,2012.0,3.0,3.000000,395.0,364,NaN,NaN,5.916472,123.70000,123.700000,-1998.0,0.169300,0.115539,0.208453
216927,0,11.0,1202,1713799.96,11651.90,2012.0,4.0,7.000000,2494.0,364,14.354224,0.006799,9.363225,2912.97500,1664.557143,-2001.0,0.263786,0.328550,0.177325

In [36]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(class_weight=class_weights , random_state=42)
model.fit(x_train , y_train)


y_pred = model.predict(x_test)
print(classification_report(y_test , y_pred))

              precision    recall  f1-score   support

           0       0.93      0.93      0.93     72596
           1       0.23      0.23      0.23      6780

    accuracy                           0.87     79376
   macro avg       0.58      0.58      0.58     79376
weighted avg       0.87      0.87      0.87     79376

In [37]:
df[df['CLAIM_FLAG'] !=1]

,SEX,INSR_BEGIN,INSR_END,EFFECTIVE_YR,INSR_TYPE,INSURED_VALUE,PREMIUM,OBJECT_ID,PROD_YEAR,SEATS_NUM,...,log_INSURED_VALUE,premium_to_value,log_PREMIUM,premium_per_seat,premium_per_capacity,vehicle_age,usage_freq,make_freq,TYPE_VEHICLE_freq,CLAIM_FLAG
0,0,2017-08-08,2018-08-07,8.0,1202,519755.22,5097.83,5000029885,2007.0,4.0,...,13.161113,0.009808,8.536570,1274.4575,849.638333,-1999.0,0.263786,0.041976,0.177325,0
1,0,2016-08-08,2017-08-07,8.0,1202,519755.22,6556.52,5000029885,2007.0,4.0,...,13.161113,0.012615,8.788215,1639.1300,1092.753333,-1999.0,0.263786,0.041976,0.177325,0
2,0,2015-08-08,2016-08-07,8.0,1202,519755.22,6556.52,5000029885,2007.0,4.0,...,13.161113,0.012615,8.788215,1639.1300,1092.753333,-1999.0,0.263786,0.041976,0.177325,0
3,0,2014-08-08,2015-08-07,8.0,1202,519755.22,5102.83,5000029885,2007.0,4.0,...,13.161113,0.009818,8.537551,1275.7075,850.471667,-1999.0,0.263786,0.041976,0.177325,0
4,0,2017-08-08,2018-08-07,8.0,1202,1400000.00,13304.87,5000029901,2010.0,4.0,...,14.151983,0.009503,9.495885,3326.2175,1900.695714,-2002.0,0.263786,0.328550,0.177325,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
508494,0,2018-02-02,2019-02-01,12.0,1202,0.00,294.51,5001350484,2018.0,4.0,...,-inf,inf,5.685313,73.6275,42.072857,-2006.0,0.263786,0.328550,0.177325,0
508495,0,2018-02-02,2019-02-01,12.0,1202,0.00,299.51,5001350489,2018.0,4.0,...,-inf,inf,5.702148,74.8775,42.787143,-2006.0,0.263786,0.328550,0.177325,0
508496,0,2018-02-02,2019-02-01,12.0,1202,0.00,294.51,5001350498,2018.0,4.0,...,-inf,inf,5.685313,73.6275,42.072857,-2006.0,0.263786,0.328550,0.177325,0
508497,0,2018-02-02,2019-02-01,12.0,1202,0.00,294.51,5001350502,2018.0,4.0,...,-inf,inf,5.685313,73.6275,42.072857,-2006.0,0.263786,0.328550,0.177325,0
508498,0,2018-02-02,2019-02-01,12.0,1202,0.00,294.51,5001350505,2018.0,4.0,...,-inf,inf,5.685313,73.6275,42.072857,-2006.0,0.263786,0.328550,0.177325,0

In [38]:
df[df['CLAIM_FLAG'] == 1]

,SEX,INSR_BEGIN,INSR_END,EFFECTIVE_YR,INSR_TYPE,INSURED_VALUE,PREMIUM,OBJECT_ID,PROD_YEAR,SEATS_NUM,...,log_INSURED_VALUE,premium_to_value,log_PREMIUM,premium_per_seat,premium_per_capacity,vehicle_age,usage_freq,make_freq,TYPE_VEHICLE_freq,CLAIM_FLAG
6,0,2015-08-08,2016-08-07,8.0,1202,1400000.00,16438.15,5000029901,2010.0,4.0,...,14.151983,0.011742,9.707360,4109.53750,2348.307143,-2002.0,0.263786,0.328550,0.177325,1
7,0,2014-08-08,2015-08-07,8.0,1202,285451.24,3931.23,5000029901,2010.0,4.0,...,12.561827,0.013772,8.276708,982.80750,561.604286,-2002.0,0.263786,0.328550,0.177325,1
48,0,2016-07-08,2017-07-07,97.0,1201,473778.00,6121.78,5000031507,2000.0,7.0,...,13.068494,0.012921,8.719608,874.54000,14.696985,-1903.0,0.240376,0.328550,0.143406,1
50,0,2014-07-08,2015-07-07,97.0,1201,473778.00,6121.78,5000031507,2000.0,7.0,...,13.068494,0.012921,8.719608,874.54000,14.696985,-1903.0,0.240376,0.328550,0.143406,1
54,0,2014-07-08,2015-07-07,97.0,1201,438578.00,5881.73,5000031508,1999.0,10.0,...,12.991293,0.013411,8.679606,588.17300,14.120680,-1902.0,0.240376,0.041976,0.143406,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
508298,0,2017-12-14,2018-12-13,6.0,1201,3500000.00,5503.81,5001315523,2018.0,8.0,...,15.068274,0.001573,8.613196,687.97625,13.213381,-2012.0,0.240376,0.328550,0.070776,1
508304,0,2018-01-16,2019-01-15,18.0,1202,956402.86,2607.92,5001311833,2017.0,1.0,...,13.770935,0.002727,7.866308,2607.92000,74.512000,-1999.0,0.263786,0.000098,0.185054,1
508335,0,2018-04-26,2019-04-25,13.0,1201,807727.15,4603.00,5001322739,2018.0,4.0,...,13.601980,0.005699,8.434464,1150.75000,11.050744,-2005.0,0.240376,0.000008,0.143406,1
508357,1,2018-01-26,2019-01-25,51.0,1201,600000.00,1868.44,5001314244,2003.0,4.0,...,13.304685,0.003114,7.532859,467.11000,4.485695,-1952.0,0.240376,0.328550,0.143406,1
508364,0,2018-03-20,2019-03-19,12.0,1202,1750000.00,12347.24,5001315598,2018.0,4.0,...,14.375126,0.007056,9.421188,3086.81000,2057.873333,-2006.0,0.263786,0.328550,0.177325,1

In [39]:
import pandas as pd

# فرض کنیم دیتافریم اسمش df باشه
# و ستون هدف اسمش "claim_flag" باشه

# رکوردهای کلاس 1 (مثبت = خسارت داشتند)
df_pos = df[df["CLAIM_FLAG"] == 1]

# رکوردهای کلاس 0 (منفی = خسارت نداشتند)
df_neg = df[df["CLAIM_FLAG"] == 0]

# تعداد مثبت‌ها
n_pos = len(df_pos)

# از کلاس منفی، به تعداد مثبت‌ها نمونه‌گیری تصادفی کنیم
df_neg_sampled = df_neg.sample(n=n_pos, random_state=42)

# ترکیب دو تا
df_balanced = pd.concat([df_pos, df_neg_sampled])

# شافل نهایی
df_balanced = df_balanced.sample(frac=1, random_state=42).reset_index(drop=True)

print(df_balanced["CLAIM_FLAG"].value_counts())

CLAIM_FLAG
1    27121
0    27121
Name: count, dtype: int64

In [40]:
df_balanced.columns

Index(['SEX', 'INSR_BEGIN', 'INSR_END', 'EFFECTIVE_YR', 'INSR_TYPE',
       'INSURED_VALUE', 'PREMIUM', 'OBJECT_ID', 'PROD_YEAR', 'SEATS_NUM',
       'CARRYING_CAPACITY', 'TYPE_VEHICLE', 'CCM_TON', 'MAKE', 'USAGE',
       'CLAIM_PAID', 'contract_duration', 'log_INSURED_VALUE',
       'premium_to_value', 'log_PREMIUM', 'premium_per_seat',
       'premium_per_capacity', 'vehicle_age', 'usage_freq', 'make_freq',
       'TYPE_VEHICLE_freq', 'CLAIM_FLAG'],
      dtype='object')

In [45]:
df.dropna(inplace=True)

In [46]:
df = feature_engineering(df_balanced)
X = df.drop(columns=['CLAIM_FLAG' , 'CLAIM_PAID' , 'MAKE' , 'USAGE' , 'INSR_BEGIN' , 'INSR_END' , 'TYPE_VEHICLE' , 'OBJECT_ID'])
y = df.CLAIM_FLAG.values

In [48]:
x_train , x_test , y_train , y_test = train_test_split(X , y , random_state=42)
x_train = x_train.replace([np.inf, -np.inf], np.nan)
x_test = x_test.replace([np.inf, -np.inf], np.nan)
model.fit(x_train , y_train)

RandomForestClassifier(class_weight={np.int64(0): np.float64(0.5466995123653495),
                                     np.int64(1): np.float64(5.853374956983433)},
                       random_state=42)

In [49]:
y_pred = model.predict(x_test)
print(classification_report(y_test , y_pred))

              precision    recall  f1-score   support

           0       0.70      0.62      0.66      6797
           1       0.66      0.73      0.69      6764

    accuracy                           0.68     13561
   macro avg       0.68      0.68      0.67     13561
weighted avg       0.68      0.68      0.67     13561

In [50]:
from catboost import CatBoostClassifier
model = CatBoostClassifier(
    iterations=400,
    depth=10,
    learning_rate=0.01,
    eval_metric='AUC',
    verbose=100,
    random_seed=42,
    task_type='GPU',
    )

model.fit(x_train , y_train , eval_set=(x_test , y_test) , plot=True)

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

Default metric period is 5 because AUC is/are not implemented for GPU

0:	test: 0.7512728	best: 0.7512728 (0)	total: 22.3ms	remaining: 8.89s
100:	test: 0.7696240	best: 0.7696240 (100)	total: 1.67s	remaining: 4.95s
200:	test: 0.7735379	best: 0.7735379 (200)	total: 3.27s	remaining: 3.24s
300:	test: 0.7752740	best: 0.7752740 (300)	total: 4.84s	remaining: 1.59s
399:	test: 0.7765202	best: 0.7765202 (399)	total: 6.51s	remaining: 0us
bestTest = 0.7765201628
bestIteration = 399

In [51]:
y_pred = model.predict(x_test)
print(classification_report(y_test , y_pred))

              precision    recall  f1-score   support

           0       0.80      0.57      0.66      6797
           1       0.66      0.86      0.75      6764

    accuracy                           0.71     13561
   macro avg       0.73      0.71      0.71     13561
weighted avg       0.73      0.71      0.71     13561

In [5]:
import pandas as pd
data  = pd.read_csv('../Dataset//Vehicle Insurance Data//motor_data11-14lats.csv')
data2 = pd.read_csv('../Dataset//Vehicle Insurance Data//motor_data14-2018.csv')
df = pd.concat([data , data2] , ignore_index = True)

In [6]:
df

,SEX,INSR_BEGIN,INSR_END,EFFECTIVE_YR,INSR_TYPE,INSURED_VALUE,PREMIUM,OBJECT_ID,PROD_YEAR,SEATS_NUM,CARRYING_CAPACITY,TYPE_VEHICLE,CCM_TON,MAKE,USAGE,CLAIM_PAID
0,0,08-AUG-13,07-AUG-14,08,1202,519755.22,7209.140,5000029885,2007.0,4.0,6.0,Pick-up,3153.0,NISSAN,Own Goods,NaN
1,0,08-AUG-12,07-AUG-13,08,1202,519755.22,7203.890,5000029885,2007.0,4.0,6.0,Pick-up,3153.0,NISSAN,Own Goods,NaN
2,0,08-AUG-11,07-AUG-12,08,1202,519755.22,7045.804,5000029885,2007.0,4.0,6.0,Pick-up,3153.0,NISSAN,Own Goods,NaN
3,0,08-JUL-11,07-AUG-11,08,1202,519755.22,287.250,5000029885,2007.0,4.0,6.0,Pick-up,3153.0,NISSAN,Own Goods,NaN
4,0,08-AUG-13,07-AUG-14,08,1202,285451.24,4286.900,5000029901,2010.0,4.0,7.0,Pick-up,2494.0,TOYOTA,Own Goods,19894.43
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
802031,0,02-FEB-18,01-FEB-19,12,1202,0.00,294.510,5001350484,2018.0,4.0,7.0,Pick-up,2400.0,TOYOTA,Own Goods,NaN
802032,0,02-FEB-18,01-FEB-19,12,1202,0.00,299.510,5001350489,2018.0,4.0,7.0,Pick-up,2400.0,TOYOTA,Own Goods,NaN
802033,0,02-FEB-18,01-FEB-19,12,1202,0.00,294.510,5001350498,2018.0,4.0,7.0,Pick-up,2400.0,TOYOTA,Own Goods,NaN
802034,0,02-FEB-18,01-FEB-19,12,1202,0.00,294.510,5001350502,2018.0,4.0,7.0,Pick-up,2400.0,TOYOTA,Own Goods,NaN
802035,0,02-FEB-18,01-FEB-19,12,1202,0.00,294.510,5001350505,2018.0,4.0,7.0,Pick-up,2400.0,TOYOTA,Own Goods,NaN

In [7]:
df['INSR_BEGIN'] = pd.to_datetime(df['INSR_BEGIN'])
df['INSR_END'] = pd.to_datetime(df['INSR_END'])

C:\Users\T A T\AppData\Local\Temp\ipykernel_10936\3724087703.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['INSR_BEGIN'] = pd.to_datetime(df['INSR_BEGIN'])
C:\Users\T A T\AppData\Local\Temp\ipykernel_10936\3724087703.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['INSR_END'] = pd.to_datetime(df['INSR_END'])

In [8]:
df

,SEX,INSR_BEGIN,INSR_END,EFFECTIVE_YR,INSR_TYPE,INSURED_VALUE,PREMIUM,OBJECT_ID,PROD_YEAR,SEATS_NUM,CARRYING_CAPACITY,TYPE_VEHICLE,CCM_TON,MAKE,USAGE,CLAIM_PAID
0,0,2013-08-08,2014-08-07,08,1202,519755.22,7209.140,5000029885,2007.0,4.0,6.0,Pick-up,3153.0,NISSAN,Own Goods,NaN
1,0,2012-08-08,2013-08-07,08,1202,519755.22,7203.890,5000029885,2007.0,4.0,6.0,Pick-up,3153.0,NISSAN,Own Goods,NaN
2,0,2011-08-08,2012-08-07,08,1202,519755.22,7045.804,5000029885,2007.0,4.0,6.0,Pick-up,3153.0,NISSAN,Own Goods,NaN
3,0,2011-07-08,2011-08-07,08,1202,519755.22,287.250,5000029885,2007.0,4.0,6.0,Pick-up,3153.0,NISSAN,Own Goods,NaN
4,0,2013-08-08,2014-08-07,08,1202,285451.24,4286.900,5000029901,2010.0,4.0,7.0,Pick-up,2494.0,TOYOTA,Own Goods,19894.43
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
802031,0,2018-02-02,2019-02-01,12,1202,0.00,294.510,5001350484,2018.0,4.0,7.0,Pick-up,2400.0,TOYOTA,Own Goods,NaN
802032,0,2018-02-02,2019-02-01,12,1202,0.00,299.510,5001350489,2018.0,4.0,7.0,Pick-up,2400.0,TOYOTA,Own Goods,NaN
802033,0,2018-02-02,2019-02-01,12,1202,0.00,294.510,5001350498,2018.0,4.0,7.0,Pick-up,2400.0,TOYOTA,Own Goods,NaN
802034,0,2018-02-02,2019-02-01,12,1202,0.00,294.510,5001350502,2018.0,4.0,7.0,Pick-up,2400.0,TOYOTA,Own Goods,NaN
802035,0,2018-02-02,2019-02-01,12,1202,0.00,294.510,5001350505,2018.0,4.0,7.0,Pick-up,2400.0,TOYOTA,Own Goods,NaN

In [12]:
df['INSR_BEGIN'].min()

Timestamp('2011-07-01 00:00:00')

In [13]:
df['INSR_BEGIN'].max()

Timestamp('2018-06-30 00:00:00')

In [14]:
df['INSR_END'].min()

Timestamp('2011-07-13 00:00:00')

In [15]:
df['INSR_END'].max()

Timestamp('2019-06-29 00:00:00')

In [20]:
df['start_year'] = pd.to_datetime(df['INSR_BEGIN']).dt.year

In [22]:
inflation_dict = {
    2011 : 21.5 ,
    2012 : 34.7 ,
    2013 : 15.6 ,
    2014 : 11.9 ,
    2015 : 9 ,
    2016 : 9.6 ,
    2017 : 31.2 ,
    2018 : 41
}

In [24]:
df['Inflation'] = df['start_year'].map(inflation_dict)
df.head()

,SEX,INSR_BEGIN,INSR_END,EFFECTIVE_YR,INSR_TYPE,INSURED_VALUE,PREMIUM,OBJECT_ID,PROD_YEAR,SEATS_NUM,CARRYING_CAPACITY,TYPE_VEHICLE,CCM_TON,MAKE,USAGE,CLAIM_PAID,start_year,Inflation
0,0,2013-08-08,2014-08-07,08,1202,519755.22,7209.140,5000029885,2007.0,4.0,6.0,Pick-up,3153.0,NISSAN,Own Goods,NaN,2013,15.6
1,0,2012-08-08,2013-08-07,08,1202,519755.22,7203.890,5000029885,2007.0,4.0,6.0,Pick-up,3153.0,NISSAN,Own Goods,NaN,2012,34.7
2,0,2011-08-08,2012-08-07,08,1202,519755.22,7045.804,5000029885,2007.0,4.0,6.0,Pick-up,3153.0,NISSAN,Own Goods,NaN,2011,21.5
3,0,2011-07-08,2011-08-07,08,1202,519755.22,287.250,5000029885,2007.0,4.0,6.0,Pick-up,3153.0,NISSAN,Own Goods,NaN,2011,21.5
4,0,2013-08-08,2014-08-07,08,1202,285451.24,4286.900,5000029901,2010.0,4.0,7.0,Pick-up,2494.0,TOYOTA,Own Goods,19894.43,2013,15.6